/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change Password */
        post: operations["change_password_api_auth_change_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Users
         * @description 成员名册 —— 管理员可见（人员管理页）。
         */
        get: operations["list_users_api_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Me
         * @description 更新本人资料 / 设置（「我的」页）。
         */
        patch: operations["update_me_api_users_me_patch"];
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Config */
        get: operations["get_config_api_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/announcements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Announcements
         * @description 当前生效的公告（未过期），按 pinned → level → 时间排序。
         */
        get: operations["list_announcements_api_announcements_get"];
        put?: never;
        /** Publish Announcement */
        post: operations["publish_announcement_api_announcements_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/announcements/{ann_id}/toggle-pin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Toggle Pin */
        post: operations["toggle_pin_api_announcements__ann_id__toggle_pin_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/announcements/{ann_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Announcement */
        delete: operations["remove_announcement_api_announcements__ann_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meetings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Meetings
         * @description 整学期组会排期（按日期升序），含报告人与在线会议信息。
         */
        get: operations["list_meetings_api_meetings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Request */
        post: operations["create_request_api_requests_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/requests/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * My Requests
         * @description 与我相关的全部请求（我发起的 + 收到的对调），按时间倒序。
         */
        get: operations["my_requests_api_requests_mine_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/requests/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pending Requests
         * @description 审批中心队列：请假/API/SSH 中待管理员处理（submitted）的请求。
         */
        get: operations["pending_requests_api_requests_pending_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/requests/processed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Processed Requests
         * @description 审批中心历史：请假/API/SSH 中已通过或已驳回的，按时间倒序。
         */
        get: operations["processed_requests_api_requests_processed_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/requests/{req_id}/advance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Advance Request */
        post: operations["advance_request_api_requests__req_id__advance_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/servers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Servers */
        get: operations["list_servers_api_servers_get"];
        put?: never;
        /** Create Server */
        post: operations["create_server_api_servers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/servers/{server_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Server */
        delete: operations["delete_server_api_servers__server_id__delete"];
        options?: never;
        head?: never;
        /** Update Server */
        patch: operations["update_server_api_servers__server_id__patch"];
        trace?: never;
    };
    "/api/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My Notifications */
        get: operations["my_notifications_api_notifications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/{notif_id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark Read */
        post: operations["mark_read_api_notifications__notif_id__read_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark All Read */
        post: operations["mark_all_read_api_notifications_read_all_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/eval/compute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Compute */
        get: operations["compute_api_eval_compute_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/eval/rank-series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Rank Series */
        get: operations["rank_series_api_eval_rank_series_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/eval/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Reports */
        get: operations["list_reports_api_eval_reports_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/eval/excellence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Excellence */
        get: operations["excellence_api_eval_excellence_get"];
        put?: never;
        /** Publish Excellence */
        post: operations["publish_excellence_api_eval_excellence_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/eval/reports/{key}/rating": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Rating */
        post: operations["submit_rating_api_eval_reports__key__rating_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/eval/reports/{key}/attendance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Attendance */
        post: operations["set_attendance_api_eval_reports__key__attendance_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/eval/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Config */
        get: operations["get_config_api_eval_config_get"];
        /** Put Config */
        put: operations["put_config_api_eval_config_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apikeys/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My Keys */
        get: operations["my_keys_api_apikeys_mine_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apikeys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Issue Key
         * @description 管理员签发：把 dmxapi 后台建好的令牌下发给某成员（审批 api 请求后调用）。
         */
        post: operations["issue_key_api_apikeys_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apikeys/{key_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke Key */
        delete: operations["revoke_key_api_apikeys__key_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/booking/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings */
        get: operations["get_settings_api_booking_settings_get"];
        /** Update Settings */
        put: operations["update_settings_api_booking_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/booking/meetings/{meeting_id}/book": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Book One */
        post: operations["book_one_api_booking_meetings__meeting_id__book_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/booking/run-auto": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Auto
         * @description 立即触发一次自动预约扫描（便于管理员手动催一次）。
         */
        post: operations["run_auto_api_booking_run_auto_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccessToken */
        AccessToken: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** AdvanceRequest */
        AdvanceRequest: {
            /** Next */
            next: string;
            /**
             * Note
             * @default
             */
            note: string;
        };
        /**
         * AnnLevel
         * @enum {string}
         */
        AnnLevel: "info" | "important" | "urgent";
        /** AnnouncementCreate */
        AnnouncementCreate: {
            /** Title */
            title: string;
            /**
             * Body
             * @default
             */
            body: string;
            /** @default info */
            level: components["schemas"]["AnnLevel"];
            /**
             * Pinned
             * @default false
             */
            pinned: boolean;
            /**
             * Audience
             * @default all
             */
            audience: string;
            /**
             * Author
             * @default
             */
            author: string;
            /** Expiresat */
            expiresAt?: string | null;
        };
        /** AnnouncementOut */
        AnnouncementOut: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Body */
            body: string;
            level: components["schemas"]["AnnLevel"];
            /** Pinned */
            pinned: boolean;
            /** Audience */
            audience: string;
            /** Author */
            author: string;
            /**
             * Publishedat
             * Format: date-time
             */
            publishedAt: string;
            /** Expiresat */
            expiresAt?: string | null;
        };
        /** ApiKeyIssue */
        ApiKeyIssue: {
            /** User Name */
            user_name: string;
            /**
             * Label
             * @default
             */
            label: string;
            /** Upstream Key */
            upstream_key: string;
            /**
             * Budget
             * @default 0
             */
            budget: number;
        };
        /** ApiKeyOut */
        ApiKeyOut: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Masked Key */
            masked_key: string;
            /** Budget */
            budget: number;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Used Rmb */
            used_rmb?: number | null;
            /** Remain Rmb */
            remain_rmb?: number | null;
        };
        /** AttendanceSet */
        AttendanceSet: {
            /** Name */
            name: string;
            /** Status */
            status: string;
        };
        /** AutoBookUpdate */
        AutoBookUpdate: {
            /** Auto Book */
            auto_book: boolean;
        };
        /** BookingSettings */
        BookingSettings: {
            /** Enabled */
            enabled: boolean;
            /** Auto Book */
            auto_book: boolean;
            /** Days Ahead */
            days_ahead: number;
        };
        /** ChangePasswordRequest */
        ChangePasswordRequest: {
            /** Old Password */
            old_password: string;
            /** New Password */
            new_password: string;
        };
        /** ConfigOut */
        ConfigOut: {
            semester: components["schemas"]["SemesterOut"];
            meetingDefault: components["schemas"]["MeetingDefaultOut"];
        };
        /** CreateRequest */
        CreateRequest: {
            kind: components["schemas"]["RequestKind"];
            /**
             * Fromdate
             * @default
             */
            fromDate: string;
            /**
             * Toname
             * @default
             */
            toName: string;
            /**
             * Todate
             * @default
             */
            toDate: string;
            /**
             * Topic
             * @default
             */
            topic: string;
            /**
             * Detail
             * @default
             */
            detail: string;
            /**
             * Reason
             * @default
             */
            reason: string;
            /**
             * Note
             * @default
             */
            note: string;
        };
        /** EvalComputeOut */
        EvalComputeOut: {
            /** Total */
            total: number;
            /** Weights */
            weights: {
                [key: string]: unknown;
            };
            /** Rows */
            rows: components["schemas"]["EvalRowOut"][];
            /** Merged */
            merged: components["schemas"]["MergedOut"][];
        };
        /** EvalConfigIO */
        EvalConfigIO: {
            /** Weights */
            weights: {
                [key: string]: unknown;
            };
            /** Filters */
            filters: {
                [key: string]: unknown;
            };
            /** Range */
            range: {
                [key: string]: unknown;
            };
            /** Progress Order */
            progress_order?: string[] | null;
        };
        /** EvalRowOut */
        EvalRowOut: {
            /** Name */
            name: string;
            /** Attitude */
            attitude: number;
            /** Polish */
            polish: number;
            /** Attrate */
            attRate: number;
            /** Discuss */
            discuss: number;
            /** Meeting */
            meeting: number;
            /** Meetingrank */
            meetingRank: number;
            /** Nattitude */
            nAttitude: number;
            /** Npolish */
            nPolish: number;
            /** Natt */
            nAtt: number;
            /** Ndisc */
            nDisc: number;
        };
        /** ExcellenceOut */
        ExcellenceOut: {
            /** Period */
            period: string;
            /** From */
            from: string;
            /** To */
            to: string;
            /** Names */
            names: string[];
            /** Count */
            count: number;
            /** Published */
            published: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** MeetingDefaultOut */
        MeetingDefaultOut: {
            /** Weekday */
            weekday: string;
            /** Time */
            time: string;
            /** Place */
            place: string;
        };
        /** MeetingOut */
        MeetingOut: {
            /** Id */
            id: string;
            /** Y */
            y: number;
            /** Mo */
            mo: number;
            /** Day */
            day: number;
            /** Mdlabel */
            mdLabel: string;
            /** Datelabel */
            dateLabel: string;
            /** Type */
            type: string;
            /** Tone */
            tone: string;
            /** Status */
            status: string;
            online?: components["schemas"]["OnlineMeetingOut"] | null;
            /** Presenters */
            presenters: components["schemas"]["PresenterOut"][];
        };
        /** MergedOut */
        MergedOut: {
            /** Name */
            name: string;
            /** Mrank */
            mRank: number;
            /** Prank */
            pRank: number;
            /** Score */
            score: number;
            /** Finalrank */
            finalRank: number;
        };
        /** NotificationOut */
        NotificationOut: {
            /** Id */
            id: string;
            /** Type */
            type: string;
            /** Title */
            title: string;
            /** Body */
            body: string;
            /** Read */
            read: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** OnlineMeetingOut */
        OnlineMeetingOut: {
            /** Url */
            url?: string | null;
            /** Provider */
            provider?: string | null;
            /** Id */
            id?: string | null;
            /** Password */
            password?: string | null;
            /** Status */
            status?: string | null;
        };
        /** PresenterOut */
        PresenterOut: {
            /** Name */
            name: string;
            /** Topic */
            topic: string;
            /**
             * Kind
             * @default
             */
            kind: string;
            /** Minutes */
            minutes?: number | null;
        };
        /** PublishExcellence */
        PublishExcellence: {
            /**
             * Count
             * @default 5
             */
            count: number;
        };
        /** RankSeriesOut */
        RankSeriesOut: {
            /** Points */
            points: {
                [key: string]: unknown;
            }[];
            /** Ranks */
            ranks: number[];
            /** Total */
            total: number;
        };
        /** RatingSubmit */
        RatingSubmit: {
            /** Presenter */
            presenter: string;
            /** Attitude */
            attitude: number;
            /** Polish */
            polish: number;
            /**
             * Top5
             * @default []
             */
            top5: string[];
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** ReportOut */
        ReportOut: {
            /** Key */
            key: string;
            /** Mo */
            mo: number;
            /** Day */
            day: number;
            /** Datelabel */
            dateLabel: string;
            /** Type */
            type: string;
            /** Presenters */
            presenters: string[];
            /** Attendance */
            attendance: {
                [key: string]: unknown;
            };
        };
        /** RequestEventOut */
        RequestEventOut: {
            /** Status */
            status: string;
            /** Note */
            note: string;
            /**
             * At
             * Format: date-time
             */
            at: string;
        };
        /**
         * RequestKind
         * @enum {string}
         */
        RequestKind: "swap" | "absence" | "api" | "ssh";
        /** RequestOut */
        RequestOut: {
            /** Id */
            id: string;
            kind: components["schemas"]["RequestKind"];
            /** From */
            from: string;
            /**
             * Toname
             * @default
             */
            toName: string;
            /**
             * Fromdate
             * @default
             */
            fromDate: string;
            /**
             * Todate
             * @default
             */
            toDate: string;
            /**
             * Topic
             * @default
             */
            topic: string;
            /**
             * Detail
             * @default
             */
            detail: string;
            /**
             * Reason
             * @default
             */
            reason: string;
            /** Status */
            status: string;
            /**
             * Incoming
             * @default false
             */
            incoming: boolean;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** History */
            history: components["schemas"]["RequestEventOut"][];
        };
        /**
         * Role
         * @enum {string}
         */
        Role: "member" | "admin";
        /** SemesterOut */
        SemesterOut: {
            /** Name */
            name: string;
            /** Short */
            short: string;
            /**
             * Start
             * Format: date
             */
            start: string;
            /**
             * End
             * Format: date
             */
            end: string;
        };
        /** ServerCreate */
        ServerCreate: {
            /** Name */
            name: string;
            /**
             * Ip
             * @default
             */
            ip: string;
            /**
             * Ssh Port
             * @default 22
             */
            ssh_port: number;
            /**
             * Gpu
             * @default
             */
            gpu: string;
            /** @default online */
            status: components["schemas"]["ServerStatus"];
            /**
             * Net
             * @default intranet
             */
            net: string;
            /**
             * Desc
             * @default
             */
            desc: string;
        };
        /** ServerOut */
        ServerOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Ip */
            ip: string;
            /** Ssh Port */
            ssh_port: number;
            /** Gpu */
            gpu: string;
            status: components["schemas"]["ServerStatus"];
            /** Net */
            net: string;
            /** Desc */
            desc: string;
        };
        /**
         * ServerStatus
         * @enum {string}
         */
        ServerStatus: "online" | "busy" | "offline";
        /** ServerUpdate */
        ServerUpdate: {
            /** Name */
            name?: string | null;
            /** Ip */
            ip?: string | null;
            /** Ssh Port */
            ssh_port?: number | null;
            /** Gpu */
            gpu?: string | null;
            status?: components["schemas"]["ServerStatus"] | null;
            /** Net */
            net?: string | null;
            /** Desc */
            desc?: string | null;
        };
        /** TokenPair */
        TokenPair: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            role: components["schemas"]["Role"];
            /** Title */
            title: string;
            /** Ssh Pubkey */
            ssh_pubkey?: string | null;
            /** Settings */
            settings: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** UserSettingsUpdate */
        UserSettingsUpdate: {
            /** Name */
            name?: string | null;
            /** Title */
            title?: string | null;
            /** Ssh Pubkey */
            ssh_pubkey?: string | null;
            /** Settings */
            settings?: {
                [key: string]: unknown;
            } | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessToken"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    change_password_api_auth_change_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_api_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"][];
                };
            };
        };
    };
    update_me_api_users_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserSettingsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_config_api_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigOut"];
                };
            };
        };
    };
    list_announcements_api_announcements_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnnouncementOut"][];
                };
            };
        };
    };
    publish_announcement_api_announcements_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnnouncementCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnnouncementOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    toggle_pin_api_announcements__ann_id__toggle_pin_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ann_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnnouncementOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_announcement_api_announcements__ann_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ann_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_meetings_api_meetings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingOut"][];
                };
            };
        };
    };
    create_request_api_requests_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    my_requests_api_requests_mine_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestOut"][];
                };
            };
        };
    };
    pending_requests_api_requests_pending_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestOut"][];
                };
            };
        };
    };
    processed_requests_api_requests_processed_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestOut"][];
                };
            };
        };
    };
    advance_request_api_requests__req_id__advance_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                req_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdvanceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_servers_api_servers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerOut"][];
                };
            };
        };
    };
    create_server_api_servers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServerCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_server_api_servers__server_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                server_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_server_api_servers__server_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                server_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServerUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    my_notifications_api_notifications_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationOut"][];
                };
            };
        };
    };
    mark_read_api_notifications__notif_id__read_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notif_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_all_read_api_notifications_read_all_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    compute_api_eval_compute_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalComputeOut"];
                };
            };
        };
    };
    rank_series_api_eval_rank_series_get: {
        parameters: {
            query: {
                name: string;
                from_?: string;
                to?: string;
                metric?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankSeriesOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_reports_api_eval_reports_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportOut"][];
                };
            };
        };
    };
    excellence_api_eval_excellence_get: {
        parameters: {
            query?: {
                count?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExcellenceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_excellence_api_eval_excellence_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublishExcellence"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExcellenceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_rating_api_eval_reports__key__rating_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RatingSubmit"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_attendance_api_eval_reports__key__attendance_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttendanceSet"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_config_api_eval_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalConfigIO"];
                };
            };
        };
    };
    put_config_api_eval_config_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvalConfigIO"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalConfigIO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    my_keys_api_apikeys_mine_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyOut"][];
                };
            };
        };
    };
    issue_key_api_apikeys_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApiKeyIssue"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_key_api_apikeys__key_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_api_booking_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingSettings"];
                };
            };
        };
    };
    update_settings_api_booking_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AutoBookUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingSettings"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    book_one_api_booking_meetings__meeting_id__book_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_auto_api_booking_run_auto_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
