"""server ssh_port

Revision ID: 190e2ebf8fcd
Revises: b2cac7992edd
Create Date: 2026-06-13 20:05:25.113093
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '190e2ebf8fcd'
down_revision: str | None = 'b2cac7992edd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ssh_port', sa.Integer(), nullable=False, server_default='22'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.drop_column('ssh_port')

    # ### end Alembic commands ###
