"""requests state machine

Revision ID: aecfc278e286
Revises: e821e0ca1461
Create Date: 2026-06-13 18:21:06.627362
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'aecfc278e286'
down_revision: str | None = 'e821e0ca1461'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requests',
    sa.Column('kind', sa.Enum('swap', 'absence', 'api', 'ssh', name='request_kind'), nullable=False),
    sa.Column('requester_id', sa.String(length=32), nullable=False),
    sa.Column('target_user_id', sa.String(length=32), nullable=True),
    sa.Column('from_date', sa.String(length=32), nullable=False),
    sa.Column('to_date', sa.String(length=32), nullable=False),
    sa.Column('topic', sa.String(length=256), nullable=False),
    sa.Column('detail', sa.String(length=256), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_requests_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_requests_requester_id'), ['requester_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_requests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_requests_target_user_id'), ['target_user_id'], unique=False)

    op.create_table('request_events',
    sa.Column('request_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('note', sa.String(length=256), nullable=False),
    sa.Column('actor_id', sa.String(length=32), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('request_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_request_events_request_id'), ['request_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_request_events_request_id'))

    op.drop_table('request_events')
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_requests_target_user_id'))
        batch_op.drop_index(batch_op.f('ix_requests_status'))
        batch_op.drop_index(batch_op.f('ix_requests_requester_id'))
        batch_op.drop_index(batch_op.f('ix_requests_kind'))

    op.drop_table('requests')
    # ### end Alembic commands ###
