"""lab: semester config announcements meetings

Revision ID: e821e0ca1461
Revises: 3892fed58d3e
Create Date: 2026-06-13 18:07:30.936568
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'e821e0ca1461'
down_revision: str | None = '3892fed58d3e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements',
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('level', sa.Enum('info', 'important', 'urgent', name='ann_level'), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('audience', sa.String(length=16), nullable=False),
    sa.Column('author', sa.String(length=64), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.Date(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lab_config',
    sa.Column('weekday', sa.String(length=8), nullable=False),
    sa.Column('time', sa.String(length=32), nullable=False),
    sa.Column('place', sa.String(length=128), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meetings',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('type', sa.Enum('progress', 'literature', name='meeting_type'), nullable=False),
    sa.Column('place', sa.String(length=128), nullable=False),
    sa.Column('time', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'cancelled', name='meeting_status'), nullable=False),
    sa.Column('online_url', sa.String(length=256), nullable=True),
    sa.Column('online_provider', sa.String(length=32), nullable=True),
    sa.Column('online_id', sa.String(length=48), nullable=True),
    sa.Column('online_status', sa.String(length=16), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meetings_date'), ['date'], unique=False)

    op.create_table('semesters',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('short', sa.String(length=32), nullable=False),
    sa.Column('start', sa.Date(), nullable=False),
    sa.Column('end', sa.Date(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('semesters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_semesters_is_current'), ['is_current'], unique=False)

    op.create_table('presenters',
    sa.Column('meeting_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('topic', sa.String(length=256), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=True),
    sa.Column('ord', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('presenters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_presenters_meeting_id'), ['meeting_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('presenters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_presenters_meeting_id'))

    op.drop_table('presenters')
    with op.batch_alter_table('semesters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_semesters_is_current'))

    op.drop_table('semesters')
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meetings_date'))

    op.drop_table('meetings')
    op.drop_table('lab_config')
    op.drop_table('announcements')
    # ### end Alembic commands ###
