"""meeting online_password + labconfig auto_book

Revision ID: f1e5034cd80c
Revises: 190e2ebf8fcd
Create Date: 2026-06-13 20:18:59.836256
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'f1e5034cd80c'
down_revision: str | None = '190e2ebf8fcd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auto_book', sa.Boolean(), nullable=False, server_default=sa.false()))

    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('online_password', sa.String(length=48), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.drop_column('online_password')

    with op.batch_alter_table('lab_config', schema=None) as batch_op:
        batch_op.drop_column('auto_book')

    # ### end Alembic commands ###
